# Generated by Django 3.2.5 on 2021-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
