# Generated by Django 3.2.5 on 2021-07-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='task',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='task',
            name='path',
        ),
    ]
